### PR TITLE
Added is_subclass_of checks to controller so RelationList works when Bolt is using extended classes

### PR DESCRIPTION
**Pull request by graham73may**
Added is_subclass_of checks to controller so RelationList works when Bolt is using extended classes. 

We've got an WIP/RFC on Hierarchical pages, as such we've had to extend the Bolt\Legacy\Content entity.

### CODE REVIEW

**Comment by ToBe998** [comment]
Tnx for your contribution. I'll give it a short test and merge/release if everything is fine.

**Comment by ToBe998** [comment]
Wouldn't it be a bit shorter to use the `instanceof` operator instead? This operator should check for bot original instance or a sub class or implementer of it.

Instead of:
```
if (!is_array($contentObjects) && (get_class($contentObjects) == "Bolt\\Legacy\\Content" || is_subclass_of($contentObjects, "Bolt\\Legacy\\Content"))) {
```

use:
```
if (!is_array($contentObjects) && ($contentObjects instanceof Bolt\\Legacy\\Content)) {
```

Just a short untested comment...

**Comment by graham73may** [comment]
I'll try this now and report back, the code in my PR was what got my Bolt

**Comment by graham73may** [comment]
@ToBe998 Just tested your instanceof check, does the job!

**Pull request merged**
