### PR TITLE
[BUG] contenttype needs to use slug not name field

### PR DESCRIPTION
**Pull request by graham73may**
Because the name field was being used instead of the slug field, this would throw errors when using relationlist with contenttypes that have a slug manually defined to be different to the name e.g. this wouldn't work:

```
news:
    name: News and opinion
    slug: news
    singular_name: News and opinion piece
    singular_slug: news-item
```

p.s. Sorry about the other commits... css file kept flagging as modified in the PR.

### CODE REVIEW

**Comment by graham73may** [comment]
Sorry branch tidying... Branch restored

**Comment by ToBe998** [comment]
Sorry, this might have been forgotten. Is this issue still open?

**Comment by graham73may** [comment]
@ToBe998 Bug still present in master - https://github.com/CondeNastDigital/cnBolt-Extensions-RelationList/blob/master/templates/_relationlist.twig#L44

**Comment by ToBe998** [comment]
Looks absolutly reasonable, we just need to check if already stored relations would still work afterwards. If not, we would need to make the service understand all possible values for a contenttype (like most other bolt services).

**Comment by ToBe998** [comment]
Merged manually.

**Pull request closed without merging**
